# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
    -   id: ruff
        args: [--fix, --config, pyproject.toml]
    -   id: ruff-format
        args: [--config, pyproject.toml]
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: bash -c "source .venv/bin/activate && pytest"
        language: system
        types: [python]
        fail_fast: true
